services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000"  # Blob Service
      - "10001:10001"  # Queue Service
      - "10002:10002"  # Table Service
    volumes:
      - azurite_data:/workspace
    command: 'azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --location /workspace --debug /workspace/debug.log'

  catcatalog:
    image: ${DOCKER_REGISTRY-}catcatalog
    build:
      context: .
      dockerfile: CatCatalog/Dockerfile
    depends_on:
      - sqlserver
      - azurite
    environment:
      - SA_PASSWORD=YourPassword123!

volumes:
  azurite_data: